---
- name: Install foreman dependencies
  yum: name={{ item }} state=latest
  with_items:
    - tftp-server
    - qemu-kvm
    - qemu-kvm-tools
    - libvirt
    - libvirt-client
    - virt-who
    - virt-what
    - fence-virtd-libvirt
    - fence-virtd-multicast
    - fence-virtd-serial
    - bpg-sans-fonts
    - virt-viewer
    - xauth
