---
# When bridge_name == physical_interface we assume that the caller already set up the bridge.
- name: Ensure bridge-utils
  yum: name=bridge-utils state=present

- name: Set bridge interface config
  template: src=ifcfg-br.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ bridge_name }}
            owner=root group=root mode=0644
  when: bridge_name != physical_interface

- name: Set eth interface config
  template: src=ifcfg-eth.j2 dest=/etc/sysconfig/network-scripts/ifcfg-{{ physical_interface }}
            owner=root group=root mode=0644
  when: bridge_name != physical_interface

- name: Disable and stop NetworkManager
  service: name=NetworkManager state=stopped enabled=no
  when: ansible_distribution != 'RedHat' and (ansible_distribution_version | version_compare('7.0', '<'))

- name: Restart network (and cross your fingers)
  service: name=network state=restarted
  when: bridge_name != physical_interface
