---
- name: Create VM images
  qemu_img: dest=/var/lib/libvirt/images/{{ item.value.name }}.qcow2 size=10000 format=qcow2 opt=preallocation=metadata state=present
  with_dict: nodes
  when: item.key not in ['foreman', 'tempest']

- name: Create VMs
  virt: name={{ item.value.name }}
        command=define
        xml="{{ lookup('template', 'server.xml.j2') }}"
  with_dict: nodes
  when: item.key not in ['foreman', 'tempest']

- name: Start VMs
  virt: name={{ item.value.name }}
        command=start
  with_dict: nodes
  when: item.key not in ['foreman', 'tempest']
