---
- name: Workarounds | Staypuft node
  hosts: staypuft
  tags: workaround
  roles:
    - { role: workarounds/staypuft-rhel7-tftp,
        when: workaround_staypuft_rhel7_tftp is defined
          and workaround_staypuft_rhel7_tftp }
