---
- name: Ensure foreman and puppet repos are enabled
  ini_file: dest=/etc/yum.repos.d/{{ item.repo }}.repo
            section={{ item.section }}
            option={{ item.option }}
            value={{ item.value }}
  with_items:
    - { repo: foreman, section: foreman, option: enabled, value: 1 }
    - { repo: foreman, section: foreman-plugins, option: enabled, value: 1 }
    - { repo: puppetlabs, section: puppetlabs-products, option: enabled, value: 1 }
    - { repo: puppetlabs, section: puppetlabs-deps, option: enabled, value: 1 }

- name: Install Ruby SCL
  template: src=ruby-scl.repo.j2 dest=/etc/yum.repos.d/ruby-scl.repo owner=root group=root mode=644

- name: Install openstack-foreman-installer rpm
  yum: name={{ openstack_foreman_installer_rpm }} state=present

- include: openstack-puppet-modules-src.yml
  when: use_opm_src is defined and use_opm_src

- include: astapor.yml
  when: use_astapor is defined and use_astapor

- name: Make /etc/hosts proper
  lineinfile: "dest=/etc/hosts regexp='.*{{hostvars[item].fqdn }}$' line='{{ hostvars[item].ansible_eth1.ipv4.address }} {{ hostvars[item].fqdn }}' state=present"
  with_items: groups.foreman

- name: Deactivate iptables
  service: name=iptables enabled=no state=stopped
  tags:
    - iptables

- name: Check for SecureRandom
  shell: grep 'SecureRandom.hex' {{ astapor_dest }}/bin/seeds.rb
  ignore_errors: True
  register: random_passwords

- name: Make passwords the same for foreman environment
  shell: "/bin/sed -i -e 's/SecureRandom.hex/\"redhat\"/' {{ item }}"
  with_items: '{{ astapor_dest }}/bin/seeds.rb'
  when: random_passwords.rc == 0

- name: Set ha_mysql vars
  lineinfile: >
    dest=/usr/share/openstack-foreman-installer/bin/seeds.rb
    regexp= {{ item.regex }}
    line="\1'{{ item.value }}'"
    backregs=yes
    state=present
  with_items:
    - { regex: '^(.*"mysql_shared_storage_device"[ ]*=> )\'192.168.203.200:/mnt/mysql\',', value: '{{ ha_mysql_storage }}' }
    - { regex: '^(.*"mysql_shared_storage_type"[ ]*=> )\'nfs\',', value: 'nfs' }
    - { regex: '^(.*"mysql_resource_group_name"[ ]*=> )\'mysqlgrp\',', value: 'mysqlgrp' }
    - { regex: '^(.*"mysql_clu_member_addrs"[ ]*=> )\'192.168.203.11 192.168.203.12 192.168.203.13\',', value: '{{ lookup('template', 'ha_mysql_clu_members.j2') }}' }
  when: use_ha_mysql is defined and use_ha_mysql

- name: Fix seed values
  lineinfile: >
    dest={{ astapor_dest }}/bin/seeds.rb
    regexp="^(.*\"{{ item.name }}\"[ ]*=> )([\"']){{ item.oldvalue }}([\"']),"
    line="\1\g<2>{{ item.newvalue }}\g<3>,"
    backrefs=yes
    state=present
  with_items: seed_values

- name: Remove the prompt in foreman_server.sh
  lineinfile: >
    dest={{ astapor_dest }}/bin/foreman_server.sh
    regexp='^read .*'
    state=absent

- name: Remove 'include passenger' line from foreman_server.sh
  lineinfile: >
    dest={{ astapor_dest }}/bin/foreman_server.sh
    regexp='^include passenger'
    state=absent

- name: Run the installer
  shell: >
    chdir={{ astapor_dest }}/bin
    creates=/tmp/foreman_client.sh
    bash -x ./foreman_server.sh
  register: installer_run
  environment:
    FOREMAN_GATEWAY: "false"
    FOREMAN_PROVISIONING: "false"
  tags:
    - foreman_install

- name: Installer stdout
  debug: var=installer_run.stdout_lines

- name: Fetch the client installer
  fetch: src=/tmp/foreman_client.sh dest=/tmp/foreman
  tags:
    - fetch_client_script
