---
- include: group_by.yml tags=groupby

- include: staypuft/prep.yml prep_hosts=staypuft

- name: Prep staypuft on a fresh box
  hosts: staypuft
  sudo: yes
  roles:
    - { role: staypuft/selinux }
    - { role: staypuft/packages, tags: ['packages'] }
    - { role: staypuft/default_network }
    - { role: staypuft/kickstart_vms }

- include: staypuft/prep.yml prep_hosts='foreman:tempest'

- name: IPtables firewall
  hosts: foreman:RedHat-6:CentOS-6
  sudo: yes
  roles:
    - { role: staypuft/firewall/iptables }

- name: Firewalld firewall
  hosts: foreman:!RedHat-6:!CentOS-6
  sudo: yes
  roles:
    - { role: staypuft/firewall/firewalld }

- name: More prep
  hosts: foreman
  sudo: yes
  roles:
    - { role: staypuft/nfs_server }

- name: Install staypuft
  hosts: foreman
  sudo: yes
  roles:
    - { role: staypuft/install }

# apply post-install workarouds
- include: ../workarounds/workarounds-staypuft-prep.yml tags=workaround

- name: Run staypuft installer
  hosts: foreman
  sudo: yes
  roles:
    - { role: staypuft/run_install }

- include: staypuft/virt-populate.yml
