---
# NFS server for glance/cinder
- name: Install nfs-utils
  yum: name=nfs-utils state=latest

- name: Create share directories
  file: path="/{{ item }}" state=directory mode=777 owner=root group=root
  with_items:
    - cinder
    - glance

- name: Manage exports
  lineinfile: dest=/etc/exports
        regexp=^\/{{ item }}
        line='/{{ item }} 192.168.0.0/16(rw,sync,no_root_squash)'
        state=present
  with_items:
    - cinder
    - glance

- name: Turn on rpcbind
  service: name=rpcbind state=started enabled=yes

- name: Turn on nfs
  service: name=nfs state=restarted enabled=yes
